### ISSUE TITLE
Husarnet + ROS2 Humble + CycloneDDS

### ISSUE THREAD

**Issue by peredwardsson** [husarnet/husarnet#100]
Is this combination supposed to work?

I used nearly the same setup as in your tutorial at https://husarnet.com/docs/tutorial-ros2, and while it worked for Foxy it no longer works for Humble. I have two computers connected via Husarnet, and I'm trying to get Ros2 traffic across Husarnet. The following is true:
- The units can ping each other via hostnames
- The ROS_DOMAIN_ID matches
- ROS_LOCALHOST_ONLY is set to 0 on both machines
- RMW_IMPLEMENTATION is set to rmw_cyclonedds_cpp on both machines
- CYCLONEDDS_URI points to a file with the following content on both machines:
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
            <Interfaces>
                    <NetworkInterface multicast="false" name="hnet0"/>
            </Interfaces>
            <AllowMulticast>false</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
            <Transport>udp6</Transport>
        </General>
        <Discovery>
            <Peers>
                [peers]
            </Peers>
            <ParticipantIndex>auto</ParticipantIndex>
            <MaxAutoParticipantIndex>100</MaxAutoParticipantIndex>
        </Discovery>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>severe</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>

```
You can see that I made some changes based on https://github.com/eclipse-cyclonedds/cyclonedds/blob/9db62d7dccb3339c6c9f5ca0f3a3c36bfb912a34/docs/manual/config/config_file_reference.rst .
- `ros2 multicast` does not work
- `ros2 topic list --no-daemon` produces, on both,
```
# ros2 node list --no-daemon
ros2: add_peer_addresses: [peer]: unknown address
``` 
for every peer in my discovery list. This happens even though I can `ping` every (online) peer. Any ideas?

**Comment by peredwardsson** [comment]
FastRTPS doesn't seem to perform better - multicast doesn't work, but it does not complain about peers.

**Comment by DominikN** [comment]
Hi @peredwardsson, we have tested Husarnet with Humble as well and with the same DDS XML profile files (FastDDS and Cyclone) as in Foxy.

We have introduced our own version of ROS docker images for ROS 2 Humble, Galactic and Foxy (both `core` and `base` versions). You will find the Docker images here: https://hub.docker.com/r/husarnet/ros/tags and the source code (with GitHub workflow pushing images on DockerHub) here: https://github.com/husarnet/ros

We did those images because we were tired of manual configuration of DDS profile files, and wanted to automate the process both for FastDDS and Cyclone (for the first one there is also a support for Discovery Server setup). Thanks to those images you don't need to provide your own DDS profile files as a bind mound volume to your containers, because they will be generated automatically. 

If your compare `ros:humble-ros-core` (compressed size 135MB) with `husarnet/ros:humble-ros-core` (compressed size 183MB) you will notice that Husarnet images are ~50MB bigger, because in our images there are two DDS implementations present (but FastDDS is always default), and there are lightweight Linux tools for XML parsing and editing. For example the XML template we are using for the Cyclone is as follows: https://github.com/husarnet/ros/blob/main/dds-config-templates/cyclonedds-simple.xml

We are going to write a blog post about it where we will share more details soon :)

We used these Docker images in action, on physical robots - for example here on ROSbot XL: https://github.com/husarion/rosbot-xl-mapping and it works great on Humble without any issues. In this repo you have also a setup for a Gazebo simulation (100% in Docker) so you can run the simulation on the first PC and control it from the RViz running on the second PC. Of course those computers need to be in the same Husarnet network.

If this setup works with ROS running in Docker, there shouldn't be any issues with running it directly on the host.

Please let me know if it helped.

**Comment by peredwardsson** [comment]
Those auto scripts look awesome!! Could you release these scripts standalone? I got it working using them so I'm very happy to include them in my dockers, but I'm unable to rebase my images on yours (due to cuda stuff).

**Comment by DominikN** [comment]
Hi @peredwardsson! 

Generating DDS configs for Husarnet on your host OS just got easier. We have just launched `husarnet-dds` project, a single binary that you can find on our GitHub page: https://github.com/husarnet/husarnet-dds

Here's a quick and simple guide to get started:

1. Download the binary:

```bash
RELEASE="v1.0.10"
ARCH="amd64"
sudo curl -L https://github.com/husarnet/husarnet-dds/releases/download/$RELEASE/husarnet-dds-linux-$ARCH -o /usr/local/bin/husarnet-dds
sudo chmod +x /usr/local/bin/husarnet-dds
```

2. Set up the environment variables for Fast DDS or Cyclone, eg.:

```bash
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
export FASTRTPS_DEFAULT_PROFILES_FILE=/my/path/to/test-fastdds-simple.xml
```

3. Generate the config:

```bash
husarnet-dds singleshot
```

And that's it! You'll now find your Husarnet DDS config under `/my/path/to/test-fastdds-simple.xml`, and the environment variables for ROS will be set up properly.
