### ISSUE TITLE
husarnet-ros no installation candidate

### ISSUE THREAD

**Issue by sachin-rr** [husarnet/husarnet#38]
HI, 
Recently, I tried the tutorials for using [husarnet & ros](https://husarnet.com/docs/tutorial-ros1)

From there, I tried to install husarnet-ros

Getting this error

```bash
sudo apt-get install husarnet-ros
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package husarnet-ros is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'husarnet-ros' has no installation candidate
```

Can you please help with this?
Thank you :)

**Comment by rubenanapu** [comment]
Hi @sachin-rr ,

if you could tell which Linux Distro you are using, it would help people who is willing to help you.

You can get the distro with:

```
lsb_release -a 

```

which would print something like:

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```
If you don't have lsb_release, you could then run:

```
cat /etc/os-release
```

which would print something like:
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

With this information, it would be easier to diagnose the problem you mentioned.

**Comment by sachin-rr** [comment]
Hi @rubenanapu 

```bash
$lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

Please let me know if other information is also required. Thank you.

**Comment by KonradPR** [comment]
Hi @sachin-rr,

the problem You are currently encountering is unfortunately connected to the fact that the husarnet-ros package is at this moment obsolete (we are working as to update the documentation You referenced).
Please try installing package husarnet rather than husarnet-ros, and the try ruining 
`ufw default deny && ufw allow in on hnet0 && ufw enable`
which should be  identical to calling 
`husarnet-firewall enable`
from husarnet-ros pacakge.
If You wish to disable the firewall use 
`ufw disable`

Best regards,
Konrad

**Comment by sachin-rr** [comment]
Hi @KonradPR 
Thank you
