### ISSUE TITLE
Ubuntu 20.10 has reached EOL

### ISSUE THREAD

**Issue by jessearmandse** [husarnet/husarnet#39]
I noticed the Dockerfiles of the samples are using Ubuntu 20.10, but they are already [end-of-life](https://fridge.ubuntu.com/2021/07/25/ubuntu-20-10-groovy-gorilla-end-of-life-reached-on-july-22-2021/). All `apt` commands return an error, when I fetch it.

Is there any issue in upgrading them to 21.04? Why the LTS release isn't being used instead?

**Comment by KonradPR** [comment]
Hi, it is my understanding that You are referencing examples provided on our blog.
Keep in mind that some of them have been made some time ago and as such some software versions may not be the latest ones.
However most of those examples showcase a general approach and there should be no problem in upgrading them.  If You come along examples that don't work after bumping up the version of Ubuntu  used in Dockerfiles please let us know and we will investigate those problems.
As for an official update to those examples, rest assured that we are constantly working in order to provide our users with the best experience possible, that being said some avenues of development may take precedence over others. We will try and update those examples in the future but unfortunately at this moment I cannot provide You with a concrete date as to when those updates will be published.

**Comment by KonradPR** [comment]
Dockerfiles in our examples have been updated to a higher Ubuntu version.
